name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "dkdw-project-frontend"
        heroku_email: "notedeagle@gmail.com"
        justlogin: true
    - run: |
            heroku container:login
            heroku container:push web --app dkdw-project-frontend
            heroku container:release web --app dkdw-project-frontend